
CREATE TABLE IF NOT EXISTS versions (
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    environment VARCHAR(100),
    application VARCHAR(200),
    version VARCHAR(100),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);