
CREATE TABLE IF NOT EXISTS users (
	id MEDIUMINT NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(200) NOT NULL,
	last_login DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);