
CREATE TABLE IF NOT EXISTS clients (
	id VARCHAR(50) NOT NULL,
	username VARCHAR(50) NOT NULL, 
	name VARCHAR(100),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	last_usage DATETIME,
	PRIMARY KEY (id)
);