{{- if .Values.ledgerAgent.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ledger.fullname" . }}-agent
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ledger.selectorLabels" . | nindent 6 }}
      component: agent
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/agent_secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ledger.selectorLabels" . | nindent 8 }}
        component: agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ledger.serviceAccountName" . }}-agent
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "agent" ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LEDGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: {{ include "ledger.fullname" . }}-agent
            - name: LEDGER_LOCATION
              valueFrom:
                secretKeyRef:
                  key: location
                  name: {{ include "ledger.fullname" . }}-agent
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: {{ include "ledger.fullname" . }}-agent
            - name: LEDGER_NAMESPACE
              value: {{ .Values.ledgerAgent.namespaced | ternary .Release.Namespace "" }}
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  key: log-level
                  name: {{ include "ledger.fullname" . }}-agent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}