{{- if .Values.ledgerAgent.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.ledgerAgent.namespaced | ternary "Role" "ClusterRole" }}
metadata:
  name: {{ include "ledger.fullname" . }}-agent
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
    component: agent
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ledger.fullname" . }}-agent-le
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
    component: agent
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}