{{- if .Values.ledgerAgent.enabled -}}
{{ $token := .Values.ledgerAgent.token | required ".Values.ledgerAgent.token is required" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ledger.fullname" . }}-agent
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
    component: agent
data:
  endpoint: {{ .Values.ledgerAgent.endpoint | b64enc }}
  location: {{ .Values.ledgerAgent.location | b64enc }}
  token: {{ $token | b64enc }}
  log-level: {{ .Values.ledgerAgent.log.level | b64enc }}
{{- end }}
