{{- if .Values.ledgerServer.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
    component: server
data:
  mysql-dsn: {{ .Values.ledgerServer.mysql.dsn | b64enc }}
  oidc-client-id: {{ .Values.ledgerServer.oidc.clientID | b64enc }}
  oidc-issuer-url: {{ .Values.ledgerServer.oidc.issuerURL | b64enc }}
  jwt-secret: {{ .Values.ledgerServer.jwt.secret | b64enc }}
  log-level: {{ .Values.ledgerServer.log.level | b64enc }}
{{- end }}
