{{- if .Values.ledgerServer.enabled -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ledger.serviceAccountName" . }}-server
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
    component: server
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
