apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ledger-agent.fullname" . }}
  labels:
    {{- include "ledger-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
