# Default values for ledger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Desired number of pods
replicaCount: 2

image:
  # image.repository -- ledger image repository
  repository: ghcr.io/stenic/ledger
  # image.pullPolicy -- ledger image pullPolicy
  pullPolicy: Always
  # image.tag -- ledger image tag (immutable tags are recommended)
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# imagePullSecrets -- Docker registry secret names as an array
imagePullSecrets: []
# nameOverride -- String to partially override fullname
nameOverride: ""
# fullnameOverride -- String to fully override fullname
fullnameOverride: ""

serviceAccount:
  # serviceAccount.create -- Specifies whether a ServiceAccount should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# podAnnotations -- Additional annotations for the pods.
podAnnotations: {}

# podSecurityContext -- Enable Controller pods' Security Context
podSecurityContext: {}
  # fsGroup: 2000

# securityContext -- Enable Controller containers' Security Context
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsUser: 100012
  runAsGroup: 100012

# resources -- Resource requests and limits for the controller
resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

# nodeSelector -- Node labels for controller pod assignment
nodeSelector: {}

# affinity -- Affinity and anti-affinity
affinity: {}

# tolerations -- Node tolerations for server scheduling to nodes with taints
tolerations: []

ledgerAgent:
  endpoint: ledger
  token: test
  log:
    level: info
