# Default values for ledger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Desired number of pods
replicaCount: 2

image:
  # image.repository -- ledger image repository
  repository: ghcr.io/stenic/ledger
  # image.pullPolicy -- ledger image pullPolicy
  pullPolicy: Always
  # image.tag -- ledger image tag (immutable tags are recommended)
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# imagePullSecrets -- Docker registry secret names as an array
imagePullSecrets: []
# nameOverride -- String to partially override fullname
nameOverride: ""
# fullnameOverride -- String to fully override fullname
fullnameOverride: ""

serviceAccount:
  # serviceAccount.create -- Specifies whether a ServiceAccount should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# podAnnotations -- Additional annotations for the pods.
podAnnotations: {}

# podSecurityContext -- Enable Controller pods' Security Context
podSecurityContext: {}
  # fsGroup: 2000

# securityContext -- Enable Controller containers' Security Context
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsUser: 100012
  runAsGroup: 100012

service:
  # service.type -- Kubernetes Service type
  type: ClusterIP
  # service.port -- Service port
  port: 80

ingress:
  # ingress.enabled -- Enable an ingress resource
  enabled: false
  # ingress.className -- Defines which ingress controller will implement the resource
  className: ""
  # ingress.annotations -- Additional ingress annotations
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  # ingress.hosts -- List of ingress hosts
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # ingress.tls -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# resources -- Resource requests and limits for the controller
resources:
  limits:
    cpu: 500m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  # autoscaling.enabled -- Enable autoscaling
  enabled: false
  # autoscaling.minReplicas -- Minimum number of replicas
  minReplicas: 2
  # autoscaling.maxReplicas -- Maximum number of replicas
  maxReplicas: 4
  # autoscaling.targetCPUUtilizationPercentage -- Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # autoscaling.targetMemoryUtilizationPercentage -- Target Memory utilization percentage
  # targetMemoryUtilizationPercentage: 80

# nodeSelector -- Node labels for controller pod assignment
nodeSelector: {}

# affinity -- Affinity and anti-affinity
affinity: {}

# tolerations -- Node tolerations for server scheduling to nodes with taints
tolerations: []

ledgerServer:
  enabled: true
  oidc:
    issuerURL: https://[keycloak-url]/auth/realms/[realm-name]
    clientID: ledger
  jwt:
    secret: ""
  mysql:
    dsn: ""
  log:
    level: info

ledgerAgent:
  enabled: true
  endpoint: http://ledger-server
  location: ""
  namespaced: false
  token: default
  log:
    level: info
